# Generated by Django 4.1 on 2023-04-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.CharField(max_length=150)),
                ("phone", models.IntegerField(max_length=15)),
                ("date", models.DateField()),
                ("desc", models.TextField()),
            ],
        ),
    ]
