# Generated by Django 4.1 on 2023-04-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact", name="phone", field=models.IntegerField(),
        ),
    ]
